dist: trusty
language: node_js
node_js:
  - "8.11.4"
  - "10.14.1"
env:
  global:
  - PATH="/tmp/ci-tools:./node_modules/.bin/:$PATH"
cache:
  yarn: true
  directories:
  - "/tmp/ci-tools"
before_install:
- curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh
  | CACHE_DIR=/tmp/ci-tools sh -s -- yarn=1.9.4
install: yarn install
script: yarn run test
deploy:
  provider: npm
  email: open-source@goodeggs.com
  api_token:
    secure: "CIn2D/TGuTtOPJM4HpD+wW73FwKzA3YGrB1b7yHiYJIkkuppKW4Uu37xGV8aO7p+qIawFqHN3BWg8gwpaz8TnQr48a8gbTbz4KRg1gsw3nK+NniiOnBwi00bZwV0KGCMyMsHmN6cTyIgi43Pc5bdn+34yRlCA+e25iKAZ+4K5o4="
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    node: "8.11.4"
