// Generated by CoffeeScript 1.4.0
(function() {
  var Aggregator, d3;

  d3 = require('d3');

  Aggregator = (function() {

    function Aggregator() {
      this.cache = {};
    }

    Aggregator.prototype.flushTo = function(queue) {
      var name, values, _ref, _results;
      _ref = this.cache;
      _results = [];
      for (name in _ref) {
        values = _ref[name];
        values.sort();
        queue.push({
          name: "" + name + ".count",
          value: values.length
        });
        queue.push({
          name: "" + name + ".min",
          value: d3.min(values)
        });
        queue.push({
          name: "" + name + ".max",
          value: d3.max(values)
        });
        queue.push({
          name: "" + name + ".mean_90",
          value: d3.quantile(values, 0.9)
        });
        _results.push(delete this.cache[name]);
      }
      return _results;
    };

    Aggregator.prototype.timing = function(name, value) {
      var _base, _ref;
      return ((_ref = (_base = this.cache)[name]) != null ? _ref : _base[name] = []).push(value);
    };

    return Aggregator;

  })();

  module.exports = Aggregator;

}).call(this);
