// Generated by CoffeeScript 1.6.3
(function() {
  var Annotation;

  Annotation = (function() {
    function Annotation() {
      this.annotation_cache = {};
    }

    Annotation.prototype.flushTo = function(queue) {
      var name, value, _ref, _results;
      _ref = this.annotation_cache;
      _results = [];
      for (name in _ref) {
        value = _ref[name];
        queue.push({
          name: name,
          value: value
        });
        _results.push(delete this.annotation_cache[name]);
      }
      return _results;
    };

    Annotation.prototype.annotation = function(stream, title, options) {
      var a, k, v, _base;
      if (options == null) {
        options = {};
      }
      a = {
        title: title
      };
      for (k in options) {
        v = options[k];
        a[k] = v;
      }
      return ((_base = this.annotation_cache)[stream] != null ? (_base = this.annotation_cache)[stream] : _base[stream] = []).push(a);
    };

    return Annotation;

  })();

  module.exports = Annotation;

}).call(this);
