// Generated by CoffeeScript 1.7.1
(function() {
  var CounterCache;

  CounterCache = (function() {
    function CounterCache() {
      this.cache = {};
    }

    CounterCache.prototype.flushTo = function(queue) {
      var metric, name, source, value, _ref, _ref1, _results;
      _ref = this.cache;
      _results = [];
      for (metric in _ref) {
        value = _ref[metric];
        _ref1 = metric.split(';'), name = _ref1[0], source = _ref1[1];
        if (source != null) {
          queue.push({
            name: name,
            value: value,
            source: source
          });
        } else {
          queue.push({
            name: name,
            value: value
          });
        }
        _results.push(delete this.cache[metric]);
      }
      return _results;
    };

    CounterCache.prototype.increment = function(name, value) {
      var _base;
      if (value == null) {
        value = 1;
      }
      if ((_base = this.cache)[name] == null) {
        _base[name] = 0;
      }
      return this.cache[name] += value;
    };

    return CounterCache;

  })();

  module.exports = CounterCache;

}).call(this);
