// Generated by CoffeeScript 1.6.3
(function() {
  var CounterCache;

  CounterCache = (function() {
    function CounterCache() {
      this.cache = {};
    }

    CounterCache.prototype.flushTo = function(queue) {
      var name, value, _ref, _results;
      _ref = this.cache;
      _results = [];
      for (name in _ref) {
        value = _ref[name];
        queue.push({
          name: name,
          value: value
        });
        _results.push(delete this.cache[name]);
      }
      return _results;
    };

    CounterCache.prototype.increment = function(name, value) {
      var _base;
      if (value == null) {
        value = 1;
      }
      if ((_base = this.cache)[name] == null) {
        _base[name] = 0;
      }
      return this.cache[name] += value;
    };

    return CounterCache;

  })();

  module.exports = CounterCache;

}).call(this);
