// Generated by CoffeeScript 1.8.0
(function() {
  var Client, Collector, EventEmitter, Worker, client, collector, config, librato, middleware, sanitize_name, worker, _ref;

  EventEmitter = require('events').EventEmitter;

  Client = require('./client');

  Worker = require('./worker');

  Collector = require('./collector');

  middleware = require('./middleware');

  _ref = {}, collector = _ref.collector, client = _ref.client, worker = _ref.worker, config = _ref.config;

  librato = new EventEmitter();

  librato.configure = function(newConfig) {
    config = newConfig;
    collector = new Collector();
    client = new Client(config);
    return worker = new Worker({
      job: librato.flush
    });
  };

  librato.increment = function(name) {
    name = sanitize_name(name);
    return collector.increment(name);
  };

  librato.timing = function(name, valueMs) {
    name = sanitize_name(name);
    return collector.timing(name, valueMs);
  };

  librato.measure = librato.timing;

  librato.start = function() {
    return worker.start();
  };

  librato.stop = function() {
    worker.stop();
    return librato.flush();
  };

  librato.flush = function() {
    var gauges, measurement, _i, _len;
    gauges = [];
    collector.flushTo(gauges);
    for (_i = 0, _len = gauges.length; _i < _len; _i++) {
      measurement = gauges[_i];
      measurement.source = config.source;
    }
    if (gauges.length) {
      return client.send({
        gauges: gauges
      }, function(err) {
        if (err != null) {
          return librato.emit('error', err);
        }
      });
    }
  };

  librato.middleware = middleware(librato);

  module.exports = librato;

  sanitize_name = function(name) {
    return name.replace(/[^-.:_\w]+/g, '_').substr(0, 255);
  };

}).call(this);

//# sourceMappingURL=librato.js.map
