// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(librato) {
    return function(_arg) {
      var requestCountKey, responseTimeKey, _ref,
        _this = this;
      _ref = _arg != null ? _arg : {}, requestCountKey = _ref.requestCountKey, responseTimeKey = _ref.responseTimeKey;
      return function(req, res, next) {
        var end;
        req._libratoStartTime = new Date;
        if (req._librato != null) {
          return next();
        }
        req._librato = true;
        librato.increment(requestCountKey != null ? requestCountKey : 'requestCount');
        end = res.end;
        res.end = function(chunk, encoding) {
          res.end = end;
          res.end(chunk, encoding);
          return librato.timing(responseTimeKey != null ? responseTimeKey : 'responseTime', new Date - req._libratoStartTime);
        };
        return next();
      };
    };
  };

}).call(this);
