// Generated by CoffeeScript 1.6.3
(function() {
  var Worker;

  Worker = (function() {
    Worker.prototype.period = 60000;

    function Worker(_arg) {
      var period, _ref;
      _ref = _arg != null ? _arg : {}, this.job = _ref.job, period = _ref.period;
      if (this.job == null) {
        throw new Error('must provide job');
      }
      if (period != null) {
        this.period = period;
      }
      this.stopped = true;
    }

    Worker.prototype.start = function() {
      var nextRun, workFn,
        _this = this;
      this.stopped = false;
      nextRun = Worker.startTime(this.period);
      workFn = function() {
        var now;
        while (true) {
          now = Date.now();
          if (now >= nextRun) {
            _this.job();
            while (nextRun <= now) {
              nextRun += _this.period;
            }
          } else {
            return (_this.timerId = setTimeout(workFn, nextRun - now));
          }
        }
      };
      return workFn();
    };

    Worker.prototype.stop = function() {
      if (this.stopped) {
        return;
      }
      this.stopped = true;
      if (this.timerId != null) {
        return clearTimeout(this.timerId);
      }
    };

    Worker.startTime = function(period) {
      var earliest;
      earliest = new Date(Date.now() + period);
      if (earliest.getSeconds() === 0) {
        return earliest.valueOf();
      }
      if (period > 30) {
        return earliest.valueOf() + (60 - earliest.getSeconds());
      } else {
        return earliest.valueOf() + (period - (earliest.getSeconds() % period));
      }
    };

    return Worker;

  })();

  module.exports = Worker;

}).call(this);
